FROM 218.205.113.98:5000/node:5.1.0

RUN npm install -g cnpm --registry=https://r.cnpmjs.org

#RUN npm config set strict-ssl false
#RUN npm install -g cnpm --registry=http://r.cnpmjs.org
#RUN npm install microtime --registry=http://r.cnpmjs.org --disturl=http://dist.cnpmjs.org


#RUN cnpm install -g  pomelo

RUN cnpm install babel@6.1.18 -g

#RUN cnpm install -g easynode@0.1.1


